os.chdir('/')
files = os.listdir()
files.remove('main.py')
files.remove('funcs.py')
files.remove('sh1106.py')
files.remove('boot.py')
files.remove('console.py')
files.remove('wifi')	
files.remove('requests.py')
files.remove('v')
files.remove('data')
file = PickList(files,scr)
os.remove(file)

